### PR TITLE
Add --platform=managed to Cloud Run command

### LINKED ISSUE #47: Update gcloud command to use --platform managed
Very soon, `--platform managed` will be required when running `gcloud beta run deploy` to deploy to the managed version of Cloud Run without prompt.

### PR DESCRIPTION
**Pull request by ahmetb**
Fixes #47

### CODE REVIEW

**Comment by jamesward** [comment]
LGTM

**Comment by jamesward** [comment]
Do we auto-publish a new image once merged?  Reason is that I just got:
```
[ ✓ ] Your application is now live here:
         WARNING: No target platform specified. This will be a required flag in a future version of the gcloud command-line tool. Pass the `--platform` flag or set the [run/platform] property to satisfy this warning.
Available platforms:
- gke: Cloud Run on Google Kubernetes Engine. Use with the `--cluster` and `--cluster-location` flags or set the [run/cluster] and [run/cluster_location] properties to specify a cluster in a given zone.
- managed: Fully managed version of Cloud Run. Use with the `--region` flag or set the [run/region] property to specify a Cloud Run region.
- kubernetes: Use a Knative-compatible kubernetes cluster. Use with the `--kubeconfig` and `--context` flags to specify a kubeconfig file and the context for connecting.

https://hello-springboot-mvn-5yonijgw4a-uc.a.run.app
```

**Comment by ahmetb** [comment]
Sometimes the button image is cached on the VM. It won't be pulled every time.

I see these images:

```
gcr cloudrun/button
DIGEST        TAGS    TIMESTAMP
73af93c5b51f  latest  2019-06-25T08:03:06
0c2d3b0ed03a          2019-06-25T08:02:09
024bf1ec411d          2019-06-24T14:13:13
```

**Comment by jamesward** [comment]
Yeah. Is there a way to see the current image's digest?

**Comment by ahmetb** [comment]
I think it shows while the shell starts.

**Comment by jamesward** [comment]
It used to but for some reason I'm not seeing that anymore. Maybe since we got the image trusted.

**Pull request merged**
