### PR TITLE
Change memory to 256 from 512

### PR DESCRIPTION
**Pull request by geshan**
- [x] 256 can be a good start for most apps

### CODE REVIEW

**Comment by geshan** [comment]
@googlebot I signed it!

**Comment by jamesward** [comment]
Java apps are the exception. :(  I think we need to `app.json` this setting and make the default 256 after that.

**Comment by geshan** [comment]
That's a good suggestion.

**Comment by jamesward** [comment]
Closing this in favor of future `app.json` support for specifying memory.

**Comment by jamesward** [comment]
BTW, the `app.json` configability is live: #175 And the default is back to 256.

**Pull request closed without merging**
