### PR TITLE
Add GIF Demo - fixes #8

### LINKED ISSUE #8: Add an animated gif in the README to show the user experience
From: https://github.com/jamesward/cloud-run-button/issues/2

### PR DESCRIPTION
**Pull request by jamesward**

### CODE REVIEW

**Comment by ahmetb** [comment]
Ah crap. We just OSSed http://github.com/googlecloudplatform/cloud-run-hello, can we re-do that? Also the quality on this one is pretty low –it would be good to re-shoot with a slightly higher quality maybe.

**Comment by jamesward** [comment]
BTW, I'm just waiting on https://github.com/GoogleCloudPlatform/cloud-run-hello/issues/1

**Comment by jamesward** [comment]
I've updated the gif to use the https://github.com/googlecloudplatform/cloud-run-hello repo.

**Comment by jamesward** [comment]
Updated to use a static image on the readme

**Comment by ahmetb** [comment]
Looks good, though bit too much anti-aliased, I think I might recapture this later on a high-DPI display like Retina Display to avoid blurriness.

**Pull request merged**
